name: Check code on push

on:
  push:
    branches:
      - dev

jobs:
  esegui-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm ci

      - name: Esegui server.js
        run: |
          npm run test:client
          npm run test:server
